//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace unison.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("unison.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Settings_About {
            get {
                return ResourceManager.GetString("Settings_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unison is a free software. It is built with the following technologies:.
        /// </summary>
        public static string Settings_AboutInfo {
            get {
                return ResourceManager.GetString("Settings_AboutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Settings_ConnectButton {
            get {
                return ResourceManager.GetString("Settings_ConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Settings_Connection {
            get {
                return ResourceManager.GetString("Settings_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to MPD.
        /// </summary>
        public static string Settings_ConnectionStatusConnected {
            get {
                return ResourceManager.GetString("Settings_ConnectionStatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string Settings_ConnectionStatusConnecting {
            get {
                return ResourceManager.GetString("Settings_ConnectionStatusConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected..
        /// </summary>
        public static string Settings_ConnectionStatusOffline {
            get {
                return ResourceManager.GetString("Settings_ConnectionStatusOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Settings_Host {
            get {
                return ResourceManager.GetString("Settings_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string Settings_License {
            get {
                return ResourceManager.GetString("Settings_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by.
        /// </summary>
        public static string Settings_MadeBy {
            get {
                return ResourceManager.GetString("Settings_MadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;s updated MpcNET.
        /// </summary>
        public static string Settings_MpcNET {
            get {
                return ResourceManager.GetString("Settings_MpcNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next track.
        /// </summary>
        public static string Settings_NextTrack {
            get {
                return ResourceManager.GetString("Settings_NextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play / pause.
        /// </summary>
        public static string Settings_PlayPause {
            get {
                return ResourceManager.GetString("Settings_PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Settings_Port {
            get {
                return ResourceManager.GetString("Settings_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous track.
        /// </summary>
        public static string Settings_PreviousTrack {
            get {
                return ResourceManager.GetString("Settings_PreviousTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        public static string Settings_Shortcuts {
            get {
                return ResourceManager.GetString("Settings_Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show window.
        /// </summary>
        public static string Settings_ShowWindow {
            get {
                return ResourceManager.GetString("Settings_ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change to your own locally installed version of the Snapcast client with an.
        /// </summary>
        public static string Settings_SnapcastInfo1 {
            get {
                return ResourceManager.GetString("Settings_SnapcastInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  absolute .
        /// </summary>
        public static string Settings_SnapcastInfo2 {
            get {
                return ResourceManager.GetString("Settings_SnapcastInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path..
        /// </summary>
        public static string Settings_SnapcastInfo3 {
            get {
                return ResourceManager.GetString("Settings_SnapcastInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch at startup.
        /// </summary>
        public static string Settings_SnapcastLauch {
            get {
                return ResourceManager.GetString("Settings_SnapcastLauch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable path.
        /// </summary>
        public static string Settings_SnapcastPath {
            get {
                return ResourceManager.GetString("Settings_SnapcastPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Settings_SnapcastPort {
            get {
                return ResourceManager.GetString("Settings_SnapcastPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Settings_SnapcastResetButton {
            get {
                return ResourceManager.GetString("Settings_SnapcastResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Snapcast window.
        /// </summary>
        public static string Settings_SnapcastWindow {
            get {
                return ResourceManager.GetString("Settings_SnapcastWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code freely available.
        /// </summary>
        public static string Settings_SourceCode1 {
            get {
                return ResourceManager.GetString("Settings_SourceCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string Settings_SourceCode2 {
            get {
                return ResourceManager.GetString("Settings_SourceCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Settings_Version {
            get {
                return ResourceManager.GetString("Settings_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume down.
        /// </summary>
        public static string Settings_VolumeDown {
            get {
                return ResourceManager.GetString("Settings_VolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume offset.
        /// </summary>
        public static string Settings_VolumeOffset {
            get {
                return ResourceManager.GetString("Settings_VolumeOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume up.
        /// </summary>
        public static string Settings_VolumeUp {
            get {
                return ResourceManager.GetString("Settings_VolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show window.
        /// </summary>
        public static string ShowWindow {
            get {
                return ResourceManager.GetString("ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapcast error.
        /// </summary>
        public static string Snapcast_Popup1 {
            get {
                return ResourceManager.GetString("Snapcast_Popup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path:.
        /// </summary>
        public static string Snapcast_Popup2 {
            get {
                return ResourceManager.GetString("Snapcast_Popup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current path:.
        /// </summary>
        public static string Snapcast_Popup3 {
            get {
                return ResourceManager.GetString("Snapcast_Popup3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can reset it in the settings if needed..
        /// </summary>
        public static string Snapcast_Popup4 {
            get {
                return ResourceManager.GetString("Snapcast_Popup4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Snapcast.
        /// </summary>
        public static string StartSnapcast {
            get {
                return ResourceManager.GetString("StartSnapcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Snapcast.
        /// </summary>
        public static string StopSnapcast {
            get {
                return ResourceManager.GetString("StopSnapcast", resourceCulture);
            }
        }
    }
}
