//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace unison.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("unison.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear queue.
        /// </summary>
        public static string Clear_Queue {
            get {
                return ResourceManager.GetString("Clear_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string FilterType_Album {
            get {
                return ResourceManager.GetString("FilterType_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string FilterType_Artist {
            get {
                return ResourceManager.GetString("FilterType_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string FilterType_Directory {
            get {
                return ResourceManager.GetString("FilterType_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string FilterType_Genre {
            get {
                return ResourceManager.GetString("FilterType_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        public static string FilterType_Song {
            get {
                return ResourceManager.GetString("FilterType_Song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string FilterType_Year {
            get {
                return ResourceManager.GetString("FilterType_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        public static string Operator_Contains {
            get {
                return ResourceManager.GetString("Operator_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        public static string Operator_Is {
            get {
                return ResourceManager.GetString("Operator_Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not.
        /// </summary>
        public static string Operator_IsNot {
            get {
                return ResourceManager.GetString("Operator_IsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play queue.
        /// </summary>
        public static string Play_Queue {
            get {
                return ResourceManager.GetString("Play_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue management.
        /// </summary>
        public static string Queue_Management {
            get {
                return ResourceManager.GetString("Queue_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Radio_Country {
            get {
                return ResourceManager.GetString("Radio_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading stations....
        /// </summary>
        public static string Radio_Loading {
            get {
                return ResourceManager.GetString("Radio_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Radio_Name {
            get {
                return ResourceManager.GetString("Radio_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stations found!.
        /// </summary>
        public static string Radio_NotFound {
            get {
                return ResourceManager.GetString("Radio_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Radio_Reset {
            get {
                return ResourceManager.GetString("Radio_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Radio_Search {
            get {
                return ResourceManager.GetString("Radio_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search station.
        /// </summary>
        public static string Radio_SearchStation {
            get {
                return ResourceManager.GetString("Radio_SearchStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Radio_Tags {
            get {
                return ResourceManager.GetString("Radio_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radios.
        /// </summary>
        public static string Radios {
            get {
                return ResourceManager.GetString("Radios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Settings_About {
            get {
                return ResourceManager.GetString("Settings_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unison is a free software. It is built with the following technologies:.
        /// </summary>
        public static string Settings_AboutInfo {
            get {
                return ResourceManager.GetString("Settings_AboutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Settings_ConnectButton {
            get {
                return ResourceManager.GetString("Settings_ConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Settings_Connection {
            get {
                return ResourceManager.GetString("Settings_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that since MPD passwords are not secure (they are sent in plain text to the server), they are saved as is in the setting file..
        /// </summary>
        public static string Settings_ConnectionPasswordInfo {
            get {
                return ResourceManager.GetString("Settings_ConnectionPasswordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string Settings_ConnectionStatus {
            get {
                return ResourceManager.GetString("Settings_ConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connected to MPD.
        /// </summary>
        public static string Settings_ConnectionStatusConnected {
            get {
                return ResourceManager.GetString("Settings_ConnectionStatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connecting....
        /// </summary>
        public static string Settings_ConnectionStatusConnecting {
            get {
                return ResourceManager.GetString("Settings_ConnectionStatusConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not connected..
        /// </summary>
        public static string Settings_ConnectionStatusOffline {
            get {
                return ResourceManager.GetString("Settings_ConnectionStatusOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Settings_Host {
            get {
                return ResourceManager.GetString("Settings_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string Settings_License {
            get {
                return ResourceManager.GetString("Settings_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made by.
        /// </summary>
        public static string Settings_MadeBy {
            get {
                return ResourceManager.GetString("Settings_MadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next track.
        /// </summary>
        public static string Settings_NextTrack {
            get {
                return ResourceManager.GetString("Settings_NextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Settings_Password {
            get {
                return ResourceManager.GetString("Settings_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play / pause.
        /// </summary>
        public static string Settings_PlayPause {
            get {
                return ResourceManager.GetString("Settings_PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Settings_Port {
            get {
                return ResourceManager.GetString("Settings_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous track.
        /// </summary>
        public static string Settings_PreviousTrack {
            get {
                return ResourceManager.GetString("Settings_PreviousTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string Settings_Shortcuts {
            get {
                return ResourceManager.GetString("Settings_Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that if the input key is not recognized, this is due to a limitation on how virtual keys work..
        /// </summary>
        public static string Settings_ShortcutsInfo {
            get {
                return ResourceManager.GetString("Settings_ShortcutsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a key....
        /// </summary>
        public static string Settings_ShortcutsKey {
            get {
                return ResourceManager.GetString("Settings_ShortcutsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show window.
        /// </summary>
        public static string Settings_ShowWindow {
            get {
                return ResourceManager.GetString("Settings_ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shuffle window allows to add random songs to your queue. Both options take into account the filter..
        /// </summary>
        public static string Settings_Shuffle1 {
            get {
                return ResourceManager.GetString("Settings_Shuffle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the filter is empty, the entire music library is taken into account..
        /// </summary>
        public static string Settings_Shuffle2 {
            get {
                return ResourceManager.GetString("Settings_Shuffle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter is queried each time you use the Add to queue or Continuous shuffle options..
        /// </summary>
        public static string Settings_Shuffle3 {
            get {
                return ResourceManager.GetString("Settings_Shuffle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a fixed number of songs to the queue. For technical reasons, it is limited to 100 random songs without a filter, and to 1000 songs with a filter..
        /// </summary>
        public static string Settings_Shuffle4 {
            get {
                return ResourceManager.GetString("Settings_Shuffle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By enabling this option, unison will automatically add songs to the queue so you never run out of songs to listen to..
        /// </summary>
        public static string Settings_Shuffle5 {
            get {
                return ResourceManager.GetString("Settings_Shuffle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change to your own locally installed version of the Snapcast client with an.
        /// </summary>
        public static string Settings_SnapcastInfo1 {
            get {
                return ResourceManager.GetString("Settings_SnapcastInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  absolute .
        /// </summary>
        public static string Settings_SnapcastInfo2 {
            get {
                return ResourceManager.GetString("Settings_SnapcastInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path..
        /// </summary>
        public static string Settings_SnapcastInfo3 {
            get {
                return ResourceManager.GetString("Settings_SnapcastInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch at startup.
        /// </summary>
        public static string Settings_SnapcastLauch {
            get {
                return ResourceManager.GetString("Settings_SnapcastLauch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable path.
        /// </summary>
        public static string Settings_SnapcastPath {
            get {
                return ResourceManager.GetString("Settings_SnapcastPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Settings_SnapcastPort {
            get {
                return ResourceManager.GetString("Settings_SnapcastPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Settings_SnapcastResetButton {
            get {
                return ResourceManager.GetString("Settings_SnapcastResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Snapcast window.
        /// </summary>
        public static string Settings_SnapcastWindow {
            get {
                return ResourceManager.GetString("Settings_SnapcastWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code freely available.
        /// </summary>
        public static string Settings_SourceCode1 {
            get {
                return ResourceManager.GetString("Settings_SourceCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string Settings_SourceCode2 {
            get {
                return ResourceManager.GetString("Settings_SourceCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update database.
        /// </summary>
        public static string Settings_UpdateDatabase {
            get {
                return ResourceManager.GetString("Settings_UpdateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Settings_Version {
            get {
                return ResourceManager.GetString("Settings_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume down.
        /// </summary>
        public static string Settings_VolumeDown {
            get {
                return ResourceManager.GetString("Settings_VolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume mute.
        /// </summary>
        public static string Settings_VolumeMute {
            get {
                return ResourceManager.GetString("Settings_VolumeMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume offset.
        /// </summary>
        public static string Settings_VolumeOffset {
            get {
                return ResourceManager.GetString("Settings_VolumeOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume up.
        /// </summary>
        public static string Settings_VolumeUp {
            get {
                return ResourceManager.GetString("Settings_VolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show window.
        /// </summary>
        public static string ShowWindow {
            get {
                return ResourceManager.GetString("ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        public static string Shuffle {
            get {
                return ResourceManager.GetString("Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding.
        /// </summary>
        public static string Shuffle_ButtonMessage1 {
            get {
                return ResourceManager.GetString("Shuffle_ButtonMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to songs....
        /// </summary>
        public static string Shuffle_ButtonMessage2 {
            get {
                return ResourceManager.GetString("Shuffle_ButtonMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done!.
        /// </summary>
        public static string Shuffle_ButtonMessage3 {
            get {
                return ResourceManager.GetString("Shuffle_ButtonMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous shuffle.
        /// </summary>
        public static string Shuffle_Continuous {
            get {
                return ResourceManager.GetString("Shuffle_Continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable continuous shuffle.
        /// </summary>
        public static string Shuffle_ContinuousEnable {
            get {
                return ResourceManager.GetString("Shuffle_ContinuousEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Shuffle_Filter {
            get {
                return ResourceManager.GetString("Shuffle_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query filter.
        /// </summary>
        public static string Shuffle_FilterQuery {
            get {
                return ResourceManager.GetString("Shuffle_FilterQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Shuffle_FilterReset {
            get {
                return ResourceManager.GetString("Shuffle_FilterReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of songs in filter:.
        /// </summary>
        public static string Shuffle_FilterSongNumber {
            get {
                return ResourceManager.GetString("Shuffle_FilterSongNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying filter....
        /// </summary>
        public static string Shuffle_Querying1 {
            get {
                return ResourceManager.GetString("Shuffle_Querying1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done!.
        /// </summary>
        public static string Shuffle_Querying2 {
            get {
                return ResourceManager.GetString("Shuffle_Querying2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to queue.
        /// </summary>
        public static string Shuffle_Queue {
            get {
                return ResourceManager.GetString("Shuffle_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs to add.
        /// </summary>
        public static string Shuffle_QueueSongs {
            get {
                return ResourceManager.GetString("Shuffle_QueueSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapcast error.
        /// </summary>
        public static string Snapcast_Popup1 {
            get {
                return ResourceManager.GetString("Snapcast_Popup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path:.
        /// </summary>
        public static string Snapcast_Popup2 {
            get {
                return ResourceManager.GetString("Snapcast_Popup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current path:.
        /// </summary>
        public static string Snapcast_Popup3 {
            get {
                return ResourceManager.GetString("Snapcast_Popup3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can reset it in the settings if needed..
        /// </summary>
        public static string Snapcast_Popup4 {
            get {
                return ResourceManager.GetString("Snapcast_Popup4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Snapcast.
        /// </summary>
        public static string StartSnapcast {
            get {
                return ResourceManager.GetString("StartSnapcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums:.
        /// </summary>
        public static string Stats_Albums {
            get {
                return ResourceManager.GetString("Stats_Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists:.
        /// </summary>
        public static string Stats_Artists {
            get {
                return ResourceManager.GetString("Stats_Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last database update:.
        /// </summary>
        public static string Stats_LastDatabaseUpdate {
            get {
                return ResourceManager.GetString("Stats_LastDatabaseUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs:.
        /// </summary>
        public static string Stats_Songs {
            get {
                return ResourceManager.GetString("Stats_Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total playtime:.
        /// </summary>
        public static string Stats_TotalPlaytime {
            get {
                return ResourceManager.GetString("Stats_TotalPlaytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time played:.
        /// </summary>
        public static string Stats_TotalTimePlayed {
            get {
                return ResourceManager.GetString("Stats_TotalTimePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating database....
        /// </summary>
        public static string Stats_UpdateDBMessage1 {
            get {
                return ResourceManager.GetString("Stats_UpdateDBMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done!.
        /// </summary>
        public static string Stats_UpdateDBMessage2 {
            get {
                return ResourceManager.GetString("Stats_UpdateDBMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPD uptime:.
        /// </summary>
        public static string Stats_Uptime {
            get {
                return ResourceManager.GetString("Stats_Uptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Snapcast.
        /// </summary>
        public static string StopSnapcast {
            get {
                return ResourceManager.GetString("StopSnapcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string Update_ButtonCheck {
            get {
                return ResourceManager.GetString("Update_ButtonCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start update.
        /// </summary>
        public static string Update_ButtonStart {
            get {
                return ResourceManager.GetString("Update_ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available! New version is.
        /// </summary>
        public static string Update_Message1 {
            get {
                return ResourceManager.GetString("Update_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install now?.
        /// </summary>
        public static string Update_Message2 {
            get {
                return ResourceManager.GetString("Update_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update available..
        /// </summary>
        public static string Update_NoUpdate {
            get {
                return ResourceManager.GetString("Update_NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version.
        /// </summary>
        public static string Update_String1 {
            get {
                return ResourceManager.GetString("Update_String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available!.
        /// </summary>
        public static string Update_String2 {
            get {
                return ResourceManager.GetString("Update_String2", resourceCulture);
            }
        }
    }
}
