//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace unison.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.1")]
        public string mpd_host {
            get {
                return ((string)(this["mpd_host"]));
            }
            set {
                this["mpd_host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6600")]
        public int mpd_port {
            get {
                return ((int)(this["mpd_port"]));
            }
            set {
                this["mpd_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mpd_password {
            get {
                return ((string)(this["mpd_password"]));
            }
            set {
                this["mpd_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool snapcast_startup {
            get {
                return ((bool)(this["snapcast_startup"]));
            }
            set {
                this["snapcast_startup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool snapcast_window {
            get {
                return ((bool)(this["snapcast_window"]));
            }
            set {
                this["snapcast_window"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("snapclient_0.26.0-1_win64")]
        public string snapcast_path {
            get {
                return ((string)(this["snapcast_path"]));
            }
            set {
                this["snapcast_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1704")]
        public int snapcast_port {
            get {
                return ((int)(this["snapcast_port"]));
            }
            set {
                this["snapcast_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int volume_offset {
            get {
                return ((int)(this["volume_offset"]));
            }
            set {
                this["volume_offset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public uint nextTrack_mod {
            get {
                return ((uint)(this["nextTrack_mod"]));
            }
            set {
                this["nextTrack_mod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("176")]
        public uint nextTrack_vk {
            get {
                return ((uint)(this["nextTrack_vk"]));
            }
            set {
                this["nextTrack_vk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public uint previousTrack_mod {
            get {
                return ((uint)(this["previousTrack_mod"]));
            }
            set {
                this["previousTrack_mod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("177")]
        public uint previousTrack_vk {
            get {
                return ((uint)(this["previousTrack_vk"]));
            }
            set {
                this["previousTrack_vk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public uint playPause_mod {
            get {
                return ((uint)(this["playPause_mod"]));
            }
            set {
                this["playPause_mod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("179")]
        public uint playPause_vk {
            get {
                return ((uint)(this["playPause_vk"]));
            }
            set {
                this["playPause_vk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public uint volumeUp_mod {
            get {
                return ((uint)(this["volumeUp_mod"]));
            }
            set {
                this["volumeUp_mod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("175")]
        public uint volumeUp_vk {
            get {
                return ((uint)(this["volumeUp_vk"]));
            }
            set {
                this["volumeUp_vk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public uint volumeDown_mod {
            get {
                return ((uint)(this["volumeDown_mod"]));
            }
            set {
                this["volumeDown_mod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("174")]
        public uint volumeDown_vk {
            get {
                return ((uint)(this["volumeDown_vk"]));
            }
            set {
                this["volumeDown_vk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public uint volumeMute_mod {
            get {
                return ((uint)(this["volumeMute_mod"]));
            }
            set {
                this["volumeMute_mod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("173")]
        public uint volumeMute_vk {
            get {
                return ((uint)(this["volumeMute_vk"]));
            }
            set {
                this["volumeMute_vk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public uint showWindow_mod {
            get {
                return ((uint)(this["showWindow_mod"]));
            }
            set {
                this["showWindow_mod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public uint showWindow_vk {
            get {
                return ((uint)(this["showWindow_vk"]));
            }
            set {
                this["showWindow_vk"] = value;
            }
        }
    }
}
